language: java
jdk:
  - openjdk14


before_install:
  - cd sitodruk-ws
  - chmod +x mvnw

install:
  - mvn clean package
  
deploy:
  provider: heroku
  api_key: <api_key>

cache:
  directories:
    - $HOME/.m2
