language: java
jdk:
- openjdk14
before_install:
- cd sitodruk-ws
- chmod +x mvnw
install:
- mvn clean package
deploy:
  provider: heroku
  api_key:
    secure: Tt4JibI4OnKkGw9DQM+YAIdoLt422W3mvsMsnxb55VinZOO2Wm0mtHL+gdLGwv4vJWiNwhZ5NOl+0Avye93K3M4frBfsP0LlzAlgrqcCIq3pNwCz8VuebQx21nEkbhKyAUOXtxbeKeTJYZ0dBT753mUqrN5PxisLvHnaj2ZvVIp9QMyNS8M5sl7GmSgBwu+RTHQyBHE7KeGd8KB6MF9BckQZRJRkETjs6rlyTMdIh8EzKiA3Qjky3M38LQWMJXdWaVpGhXezliKu5x+UoBD/6NoYBKUe2FWL2+/UKL3AA5RBO4RFWvZchTLgWWryJ0fsQroOyrfYRSfHvGjs1q5kzRw2r4JD9EZBex+aPQ/mjfnFoBF65H92p8szZIIJeqbLb+ivYupRcYlMfseT2t3aBXdUFetTjdrXi6Gws1iV6ISZ5ATxuuzHzghpItE9dKlVg72Qe3jl1quLeqWlx1A2J9zZr2dFzR7Rnrz1t/4SY3PL/DfsFAkf7dncHs51VC4HAckBYhq3GU7BOkMPQTLDxI+NkoqnmkrebSDnqxuxPnyRPqxpOVNrKsX7zJMFNTO1ljoy488IZ5yQKSJxpg77uJGb2cHvnaHI04xCJTvQ8vjWM19ewhHKF9v5W8XaF3zAiV0I82baJeDtVLLQqlBDxlBAG7lf2Xs0vPjvsgV4GBE=
  app: screen-printing-application
  on:
    repo: krystiankowalski95/screen-printing
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
    secure: Tt4JibI4OnKkGw9DQM+YAIdoLt422W3mvsMsnxb55VinZOO2Wm0mtHL+gdLGwv4vJWiNwhZ5NOl+0Avye93K3M4frBfsP0LlzAlgrqcCIq3pNwCz8VuebQx21nEkbhKyAUOXtxbeKeTJYZ0dBT753mUqrN5PxisLvHnaj2ZvVIp9QMyNS8M5sl7GmSgBwu+RTHQyBHE7KeGd8KB6MF9BckQZRJRkETjs6rlyTMdIh8EzKiA3Qjky3M38LQWMJXdWaVpGhXezliKu5x+UoBD/6NoYBKUe2FWL2+/UKL3AA5RBO4RFWvZchTLgWWryJ0fsQroOyrfYRSfHvGjs1q5kzRw2r4JD9EZBex+aPQ/mjfnFoBF65H92p8szZIIJeqbLb+ivYupRcYlMfseT2t3aBXdUFetTjdrXi6Gws1iV6ISZ5ATxuuzHzghpItE9dKlVg72Qe3jl1quLeqWlx1A2J9zZr2dFzR7Rnrz1t/4SY3PL/DfsFAkf7dncHs51VC4HAckBYhq3GU7BOkMPQTLDxI+NkoqnmkrebSDnqxuxPnyRPqxpOVNrKsX7zJMFNTO1ljoy488IZ5yQKSJxpg77uJGb2cHvnaHI04xCJTvQ8vjWM19ewhHKF9v5W8XaF3zAiV0I82baJeDtVLLQqlBDxlBAG7lf2Xs0vPjvsgV4GBE=
